"""Popula tabela de serviços

Revision ID: beba63c42dc1
Revises: 
Create Date: 2025-04-13 17:15:17.910757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beba63c42dc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendente', 'finalizado', 'cancelado', name='estado'), nullable=False),
    sa.ForeignKeyConstraint(['clienteId'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_servico',
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], )
    )
    op.create_table('clientes_agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idAgendamento', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAgendamento'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes_agendamentos')
    op.drop_table('agendamento_servico')
    op.drop_table('agendamentos')
    op.drop_table('servico')
    op.drop_table('cliente')
    # ### end Alembic commands ###
